services:
  # Backend Web Service
  - type: web
    name: crm-idx-backend
    env: node
    region: oregon
    branch: main
    root: backend
    plan: free
    autoDeploy: true
    buildCommand: "npm install"
    startCommand: "node src/index.js"
    envVars:
      - key: MONGO_URI
        value: mongodb://mongo:27017/crmidx

  # Frontend Static Site
  - type: static
    name: crm-idx-frontend
    env: node
    region: oregon
    branch: main
    root: frontend
    plan: free
    autoDeploy: true
    buildCommand: "npm install && npm run build"
    publishPath: dist

  # MongoDB Private Service
  - type: private_service
    name: mongo
    env: docker
    region: oregon
    plan: free
    dockerfilePath: Dockerfile.mongo
