services:
  - type: web
    name: crm-idx-backend
    env: node
    region: oregon
    branch: main
    root: backend
    plan: free
    autoDeploy: true
    buildCommand: "npm install"
    startCommand: "node src/index.js"

  - type: static
    name: crm-idx-frontend
    env: node
    region: oregon
    branch: main
    root: frontend
    plan: free
    autoDeploy: true
    buildCommand: "npm install && npm run build"
    publishPath: dist
