services:
  # Backend (Express API / CRM)
  - type: web
    name: crm-idx-backend
    env: node
    region: oregon
    branch: main
    root: backend
    plan: free
    autoDeploy: true
    buildCommand: "npm install"
    startCommand: "node src/index.js"

  # Frontend (Vite/React)
  - type: static
    name: crm-idx-frontend
    env: node
    region: oregon
    branch: main
    root: frontend
    plan: free
    autoDeploy: true
    buildCommand: "npm install && npm run build"
    publishPath: dist

  # Cloudflare Worker Proxy (IDX feed)
  # Optional: keep separate if you deploy on Cloudflare
  # Otherwise Render won't build Workers directly
